name: "Workflow"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alexfayers/todo-to-issue-action@master"
        id: "todo"
        with:
          PROJECTS_SECRET: ${{ secrets.PROJECTS_SECRET }}
